- name: Continuous Deployment
  hosts: localhost
  connection: local

  tasks:

    - set_fact:
        version: 1.0.0 #version can be "latest" (non-production)

    - name: Deploy litecoin Helm Chart
      command: helm upgrade --install litecoin ./charts/litecoin --version {{ version }}
      args:
        chdir: "../"

    - name: Verify pods are ready
      command: kubectl get pods -l app=litecoin -o jsonpath='{.items[*].status.containerStatuses[*].ready}'
      register: pod
      until: "'false' not in pod.stdout | lower"
      retries: 5
      delay: 30
